services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    restart: on-failure
    networks:
      - my-network

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - my-network

  mongo:
    image: mongo:alpine
    ports:
      - 27017:27017
    networks:
      - my-network

  # postgres:
  #   image: postgres:alpine
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - my-network


networks:
  my-network:
    driver: bridge