version: 'version'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: on-failure
    networks:
      - my-network
  database:
    image: postgres:13
    ports:
      - 5432:5432
      
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
